/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManageRecords;

import Business.Business;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gerrysu
 */
public class AssignFacultyJPanel extends javax.swing.JPanel {
    JPanel CardSequencePanel;
    Business business;
    FacultyProfile facultyProfile;
    Department department;
    /**
     * Creates new form AssignFacultyJPanel
     */
    public AssignFacultyJPanel(Business b, JPanel clp, FacultyProfile fp) {
        this.business = b;
        this.CardSequencePanel = clp;
        this.facultyProfile = fp;
        this.department = b.getDepartment(); // Get the main department
        
        initComponents();
        
        lblFacultyName.setText(fp.getPerson().getName());
        populateCourseOfferings();
    }
    
    private void populateCourseOfferings() {
        // We need to get the "current" semester's course schedule
        // Let's assume the department has a method to get the current schedule.
        // This relies on ConfigureABusiness.java setting up a semester.
        // A more robust app would have a semester selector.
        
        // This path is based on the available files (Department -> CourseSchedule)
        CourseSchedule cs = department.getCourseSchedule("Fall 2025"); // Assuming "Fall2025" is the current semester
        
        if (cs == null) {
            JOptionPane.showMessageDialog(this, "No course schedule found for Fall2025. Cannot assign faculty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Populate the combo box
        DefaultComboBoxModel<CourseOffer> model = (DefaultComboBoxModel<CourseOffer>) cmbCourseOfferings.getModel();
        model.removeAllElements();
        
        for (CourseOffer co : cs.getSchedule()) {
            model.addElement(co); // CourseOffer's toString() will be used.
        }
        
        // We need to make sure CourseOffer.java has a good toString() method.
        // If not, this will look strange.
        // Assuming CourseOffer.toString() returns something like "INFO5100 - AED"
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFacultyLabel = new javax.swing.JLabel();
        lblFacultyName = new javax.swing.JLabel();
        lblAssignTo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnConfirmAssignment = new javax.swing.JButton();
        cmbCourseOfferings = new javax.swing.JComboBox<>();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("Assign Faculty to Course");

        lblFacultyLabel.setText("Faculty:");

        lblFacultyName.setText("[Faculty Name]");

        lblAssignTo.setText("Assign to CourseOffering:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnConfirmAssignment.setText("Confirm Assignment");
        btnConfirmAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAssignmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnConfirmAssignment))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFacultyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAssignTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFacultyName)
                                    .addComponent(cmbCourseOfferings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyLabel)
                    .addComponent(lblFacultyName))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignTo)
                    .addComponent(cmbCourseOfferings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnConfirmAssignment)
                .addGap(38, 38, 38)
                .addComponent(btnBack)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAssignmentActionPerformed
        // TODO add your handling code here:
        // 1. Get the selected CourseOffer from the combo box
        CourseOffer selectedCourseOffer = (CourseOffer) cmbCourseOfferings.getSelectedItem();
        
        if (selectedCourseOffer == null) {
            JOptionPane.showMessageDialog(this, "Please select a course offering to assign.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. Perform the assignment
        // The CourseOffer object should have a method to set the faculty
        selectedCourseOffer.assignFaculty(facultyProfile);
        
        // --- MODIFICATION: Set the faculty's department ---
        // This is now valid because we modified FacultyProfile.java
        facultyProfile.setDepartment(this.department); // Explicitly set department
        // --- END MODIFICATION ---

        // 3. Give confirmation
        JOptionPane.showMessageDialog(this, 
                "Faculty " + facultyProfile.getPerson().getName() + " has been assigned to \n" +
                selectedCourseOffer.getCourse().getName() + ".", 
                "Assignment Successful", 
                JOptionPane.INFORMATION_MESSAGE);
                
        // 4. Go back
        btnBackActionPerformed(evt);
    }//GEN-LAST:event_btnConfirmAssignmentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Go back (no refresh needed unless we add assignment status to the table)
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
        
        // --- FIX: Refresh the ManageRecordsJPanel table ---
        for (java.awt.Component c : CardSequencePanel.getComponents()) {
            if (c instanceof ManageRecordsJPanel) {
                ((ManageRecordsJPanel) c).populateFacultyTable(); 
                break;
            }
        }         
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmAssignment;
    private javax.swing.JComboBox<CourseOffer> cmbCourseOfferings;
    private javax.swing.JLabel lblAssignTo;
    private javax.swing.JLabel lblFacultyLabel;
    private javax.swing.JLabel lblFacultyName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
