/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManageRecords;

import Business.Business;
import Business.UserAccounts.UserAccountDirectory;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;

import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author gerrysu
 */
public class ManageRecordsJPanel extends javax.swing.JPanel {
    
    JPanel CardSequencePanel;
    Business business;
    Department department;

    /**
     * Creates new form ManageRecordsJPanel
     */
    public ManageRecordsJPanel(Business b, JPanel clp) {
        this.business = b;
        this.CardSequencePanel = clp;
        this.department = b.getDepartment();
        
        initComponents();
        
        populateFacultyTable();
        populateStudentTable();
    }
    
    public void populateFacultyTable(ArrayList<FacultyProfile> facultyList) {
        DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel();
        model.setRowCount(0);

        if (facultyList == null) {
            return; // No faculty in the list
        }
        
        for (FacultyProfile fp : facultyList) {
            Person person = fp.getPerson();
            if (person != null) {
                Object[] row = new Object[4];
                row[0] = person.getPersonId();
                row[1] = person.getName();
                row[2] = person.getEmail();
                row[3] = department.getName(); 
                model.addRow(row);
            }
        }
    }
    
    public void populateFacultyTable() {
        // --- MODIFIED TO USE THE OVERLOADED METHOD ---
        FacultyDirectory facultyDirectory = department.getFacultyDirectory();
        if (facultyDirectory != null) {
            populateFacultyTable(facultyDirectory.getTeacherList());
        }
    }

    public void populateStudentTable(ArrayList<StudentProfile> studentList) {
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel(); // Assuming your student table is named tblStudents
        model.setRowCount(0);

        if (studentList == null) {
            return; // No students in the list
        }

        for (StudentProfile sp : studentList) {
            Person person = sp.getPerson(); // StudentProfile should have an associated Person
            if (person != null) {
                Object[] row = new Object[6];
                row[0] = person.getPersonId(); 
                row[1] = person.getName();
                row[2] = person.getEmail();
                row[3] = department.getName(); // Added Department
                row[4] = sp.getTranscript().getAcademicStatus(); // Assignment requirement [source: 36]
                row[5] = String.format("%.2f", sp.getTranscript().calculateOverallGPA()); // Format GPA
                // --- END MODIFICATION ---
                model.addRow(row);
            }
        }
    }
    
    public void populateStudentTable() {
        StudentDirectory studentDirectory = department.getStudentDirectory();
        if (studentDirectory != null) {
            populateStudentTable(studentDirectory.getStudentlist());
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        facultyPanel = new javax.swing.JPanel();
        facultyScrollPane = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        btnViewEditFaculty = new javax.swing.JButton();
        btnDeleteFaculty = new javax.swing.JButton();
        txtFacultySearch = new javax.swing.JTextField();
        btnSearchFacultyById = new javax.swing.JButton();
        btnSearchFacultyByName = new javax.swing.JButton();
        btnSearchFacultyByDept = new javax.swing.JButton();
        btnAssignFaculty = new javax.swing.JButton();
        btnRefreshFacultyList = new javax.swing.JButton();
        studentPanel = new javax.swing.JPanel();
        txtStudentSearch = new javax.swing.JTextField();
        btnSearchStudentById = new javax.swing.JButton();
        btnSearchStudentByName = new javax.swing.JButton();
        btnSearchStudentByDept = new javax.swing.JButton();
        studentScrollPane = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnViewEditStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnRefreshStudentList = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("Manage Student & Faculty Records");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Name", "Email", "Dept Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        facultyScrollPane.setViewportView(tblFaculty);

        btnViewEditFaculty.setText("View / Edit Details");

        btnDeleteFaculty.setText("Delete Record");

        btnSearchFacultyById.setText("Search by ID");
        btnSearchFacultyById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFacultyByIdActionPerformed(evt);
            }
        });

        btnSearchFacultyByName.setText("Search by Name");
        btnSearchFacultyByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFacultyByNameActionPerformed(evt);
            }
        });

        btnSearchFacultyByDept.setText("Search by Dept");
        btnSearchFacultyByDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFacultyByDeptActionPerformed(evt);
            }
        });

        btnAssignFaculty.setText("Assign to Course/Dept");

        btnRefreshFacultyList.setText("Refresh Table");
        btnRefreshFacultyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshFacultyListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout facultyPanelLayout = new javax.swing.GroupLayout(facultyPanel);
        facultyPanel.setLayout(facultyPanelLayout);
        facultyPanelLayout.setHorizontalGroup(
            facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultyScrollPane)
                    .addComponent(txtFacultySearch)
                    .addGroup(facultyPanelLayout.createSequentialGroup()
                        .addComponent(btnSearchFacultyById, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchFacultyByName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchFacultyByDept, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(facultyPanelLayout.createSequentialGroup()
                        .addComponent(btnViewEditFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAssignFaculty)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshFacultyList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        facultyPanelLayout.setVerticalGroup(
            facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFacultySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchFacultyById)
                    .addComponent(btnSearchFacultyByName)
                    .addComponent(btnSearchFacultyByDept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facultyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewEditFaculty)
                    .addComponent(btnDeleteFaculty)
                    .addComponent(btnAssignFaculty)
                    .addComponent(btnRefreshFacultyList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Faculty", facultyPanel);

        btnSearchStudentById.setText("Search by ID");
        btnSearchStudentById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentByIdActionPerformed(evt);
            }
        });

        btnSearchStudentByName.setText("Search by Name");
        btnSearchStudentByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentByNameActionPerformed(evt);
            }
        });

        btnSearchStudentByDept.setText("Search by Dept");
        btnSearchStudentByDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentByDeptActionPerformed(evt);
            }
        });

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Dept", "Academic Status", "Overall GPT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentScrollPane.setViewportView(tblStudents);

        btnViewEditStudent.setText("View / Edit Details");

        btnDeleteStudent.setText("Delete Record");
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        btnRefreshStudentList.setText("Refresh Table");
        btnRefreshStudentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshStudentListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentScrollPane)
                    .addComponent(txtStudentSearch)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addComponent(btnSearchStudentById, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchStudentByName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchStudentByDept, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addComponent(btnViewEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshStudentList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchStudentById)
                    .addComponent(btnSearchStudentByName)
                    .addComponent(btnSearchStudentByDept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewEditStudent)
                    .addComponent(btnDeleteStudent)
                    .addComponent(btnRefreshStudentList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Student", studentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchFacultyByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFacultyByIdActionPerformed
        // TODO add your handling code here:
        String searchId = txtFacultySearch.getText().trim();
        if (searchId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Faculty ID to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Use the existing findFacultyByPersonId method
        FacultyProfile foundFaculty = department.getFacultyDirectory().findFacultyByPersonId(searchId);

        ArrayList<FacultyProfile> searchResults = new ArrayList<>();
        if (foundFaculty != null) {
            searchResults.add(foundFaculty); // Found, add to list
        }

        // Refresh the table using the new populate method
        populateFacultyTable(searchResults);

        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No faculty found with ID: " + searchId, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchFacultyByIdActionPerformed

    private void btnSearchStudentByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentByIdActionPerformed
        // TODO add your handling code here:
        // --- "Search by ID" is implemented ---
        String searchId = txtStudentSearch.getText().trim();
        if (searchId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Use the findStudent method from StudentDirectory
        StudentProfile foundStudent = department.getStudentDirectory().findStudent(searchId);
        
        ArrayList<StudentProfile> searchResults = new ArrayList<>();
        if (foundStudent != null) {
            searchResults.add(foundStudent); // Found, add to list
        } 
        
        // Refresh the table using the new populate method
        populateStudentTable(searchResults); 
        
        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No student found with ID: " + searchId, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchStudentByIdActionPerformed

    private void btnRefreshFacultyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshFacultyListActionPerformed
        // TODO add your handling code here:
        txtFacultySearch.setText("");
        populateFacultyTable(); // Reload all faculty
    }//GEN-LAST:event_btnRefreshFacultyListActionPerformed

    private void btnRefreshStudentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshStudentListActionPerformed
        // TODO add your handling code here:
        txtStudentSearch.setText("");
        populateStudentTable(); // Reload all students
    }//GEN-LAST:event_btnRefreshStudentListActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Go back to the previous panel
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchStudentByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentByNameActionPerformed
        // TODO add your handling code here:
        String searchName = txtStudentSearch.getText().trim();
        if (searchName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a name to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Call the new method we just added to StudentDirectory.java
        ArrayList<StudentProfile> searchResults = department.getStudentDirectory().searchStudentByName(searchName);
        
        // Use the overloaded populate method to refresh the table
        populateStudentTable(searchResults); 
        
        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No student found with name matching: " + searchName, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchStudentByNameActionPerformed

    private void btnSearchStudentByDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentByDeptActionPerformed
        // TODO add your handling code here:
                String searchDept = txtStudentSearch.getText().trim();
        if (searchDept.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a department name to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<StudentProfile> searchResults = new ArrayList<>();
        
        // Check if the search term matches the current department's name (case-insensitive)
        if (department.getName().equalsIgnoreCase(searchDept)) {
            // If it matches, return all students from this department
            searchResults = department.getStudentDirectory().getStudentlist();
        }
        // If it doesn't match, searchResults remains empty.
        
        populateStudentTable(searchResults); 
        
        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No students found for department: " + searchDept, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchStudentByDeptActionPerformed

    private void btnSearchFacultyByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFacultyByNameActionPerformed
        // TODO add your handling code here:
                String searchName = txtFacultySearch.getText().trim();
        if (searchName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a name to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Call the new method we just added to FacultyDirectory.java
        ArrayList<FacultyProfile> searchResults = department.getFacultyDirectory().searchFacultyByName(searchName);

        // Use the overloaded populate method to refresh the table
        populateFacultyTable(searchResults);

        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No faculty found with name matching: " + searchName, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchFacultyByNameActionPerformed

    private void btnSearchFacultyByDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFacultyByDeptActionPerformed
        // TODO add your handling code here:
                String searchDept = txtFacultySearch.getText().trim();
        if (searchDept.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a department name to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<FacultyProfile> searchResults = new ArrayList<>();

        // Check if the search term matches the current department's name (case-insensitive)
        if (department.getName().equalsIgnoreCase(searchDept)) {
            // If it matches, return all faculty from this department
            searchResults = department.getFacultyDirectory().getTeacherList();
        }
        // If it doesn't match, searchResults remains empty.

        populateFacultyTable(searchResults);

        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No faculty found for department: " + searchDept, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchFacultyByDeptActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        // TODO add your handling code here:
            // 1. Get the selected row
        int selectedRow = tblStudents.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student from the table to delete.", "No Student Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Get the Student ID from the table (column 0)
        String studentId = (String) tblStudents.getValueAt(selectedRow, 0);

        // 3. Show confirmation dialog
        int dialogResult = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete student " + studentId + "?\nThis will also delete their associated Person and User Account records.",
                "Confirm Deletion", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);
        
        if (dialogResult == JOptionPane.YES_OPTION) {
            // 4. Proceed with deletion
            try {
                // Get the directories
                StudentDirectory studentDirectory = department.getStudentDirectory();
                UserAccountDirectory userAccountDirectory = business.getUserAccountDirectory();
                PersonDirectory personDirectory = department.getPersonDirectory();

                // 5. Execute deletion in order (Profile -> Account -> Person)
                boolean profileRemoved = studentDirectory.removeStudentById(studentId);
                boolean accountRemoved = userAccountDirectory.removeUserAccountByPersonId(studentId);
                boolean personRemoved = personDirectory.removePersonById(studentId);
                
                // 6. Provide feedback
                if (profileRemoved && accountRemoved && personRemoved) {
                    JOptionPane.showMessageDialog(this, "Student " + studentId + " and all associated records have been deleted.", "Deletion Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // This indicates a potential data integrity issue
                    String feedback = "Partial deletion. Please check data:\n";
                    if (!profileRemoved) feedback += "- Student Profile not found or not removed.\n";
                    if (!accountRemoved) feedback += "- User Account not found or not removed.\n";
                    if (!personRemoved) feedback += "- Person record not found or not removed.\n";
                    JOptionPane.showMessageDialog(this, feedback, "Deletion Warning", JOptionPane.WARNING_MESSAGE);
                }
                
                // 7. Refresh the table
                populateStudentTable();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "An error occurred during deletion: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignFaculty;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteFaculty;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnRefreshFacultyList;
    private javax.swing.JButton btnRefreshStudentList;
    private javax.swing.JButton btnSearchFacultyByDept;
    private javax.swing.JButton btnSearchFacultyById;
    private javax.swing.JButton btnSearchFacultyByName;
    private javax.swing.JButton btnSearchStudentByDept;
    private javax.swing.JButton btnSearchStudentById;
    private javax.swing.JButton btnSearchStudentByName;
    private javax.swing.JButton btnViewEditFaculty;
    private javax.swing.JButton btnViewEditStudent;
    private javax.swing.JPanel facultyPanel;
    private javax.swing.JScrollPane facultyScrollPane;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JScrollPane studentScrollPane;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblFaculty;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtFacultySearch;
    private javax.swing.JTextField txtStudentSearch;
    // End of variables declaration//GEN-END:variables
}
