/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManageRecords;

import Business.Business;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;

import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author gerrysu
 */
public class ManageRecordsJPanel extends javax.swing.JPanel {
    
    JPanel CardSequencePanel;
    Business business;
    Department department;

    /**
     * Creates new form ManageRecordsJPanel
     */
    public ManageRecordsJPanel(Business b, JPanel clp) {
        this.business = b;
        this.CardSequencePanel = clp;
        this.department = b.getDepartment();
        
        initComponents();
        
        populateFacultyTable();
    }
    
    public void populateFacultyTable() {
        DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel(); // Assuming your faculty table is named tblFaculty
        model.setRowCount(0);

        FacultyDirectory facultyDirectory = department.getFacultyDirectory();

        if (facultyDirectory != null && facultyDirectory.getTeacherList() != null) {
            for (FacultyProfile fp : facultyDirectory.getTeacherList()) {
                Person person = fp.getPerson(); // FacultyProfile should have an associated Person
                if (person != null) {
                    Object[] row = new Object[4];
                    // --- MODIFIED HERE ---
                    // Store the Person ID string for display, instead of the whole object
                    row[0] = person.getPersonId(); 
                    // --- END MODIFICATION ---
                    row[1] = person.getName();
                    row[2] = person.getEmail();
                    row[3] = department.getName(); // Assuming they are all in this department
                    model.addRow(row);
                }
            }
        }
    }

    public void populateStudentTable(ArrayList<StudentProfile> studentList) {
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel(); // Assuming your student table is named tblStudents
        model.setRowCount(0);

        if (studentList == null) {
            return; // No students in the list
        }

        for (StudentProfile sp : studentList) {
            Person person = sp.getPerson(); // StudentProfile should have an associated Person
            if (person != null) {
                Object[] row = new Object[5];
                // --- MODIFIED HERE ---
                // Store the Person ID string for display, instead of the whole object
                row[0] = person.getPersonId(); 
                // --- END MODIFICATION ---
                row[1] = person.getName();
                row[2] = person.getEmail();
                row[3] = sp.getTranscript().getAcademicStatus(); // Assignment requirement [source: 36]
                row[4] = String.format("%.2f", sp.getTranscript().calculateOverallGPA()); // Format GPA
                model.addRow(row);
            }
        }
    }  
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        facultyPanel = new javax.swing.JPanel();
        facultyScrollPane = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        btnViewEditFaculty = new javax.swing.JButton();
        btnDeleteFaculty = new javax.swing.JButton();
        txtFacultySearch = new javax.swing.JTextField();
        btnSearchFacultyById = new javax.swing.JButton();
        btnSearchFacultyByName = new javax.swing.JButton();
        btnSearchFacultyByDept = new javax.swing.JButton();
        btnAssignFaculty = new javax.swing.JButton();
        btnRefreshFacultyList = new javax.swing.JButton();
        studentPanel = new javax.swing.JPanel();
        txtStudentSearch = new javax.swing.JTextField();
        btnSearchStudentById = new javax.swing.JButton();
        btnSearchStudentByName = new javax.swing.JButton();
        btnSearchStudentByDept = new javax.swing.JButton();
        studentScrollPane = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnViewEditStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnRefreshStudentList = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("Manage Student & Faculty Records");

        btnBack.setText("<< Back");

        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Name", "Email", "Dept Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        facultyScrollPane.setViewportView(tblFaculty);

        btnViewEditFaculty.setText("View / Edit Details");

        btnDeleteFaculty.setText("Delete Record");

        btnSearchFacultyById.setText("Search by ID");
        btnSearchFacultyById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFacultyByIdActionPerformed(evt);
            }
        });

        btnSearchFacultyByName.setText("Search by Name");

        btnSearchFacultyByDept.setText("Search by Dept");

        btnAssignFaculty.setText("Assign to Course/Dept");

        btnRefreshFacultyList.setText("Refresh Table");

        javax.swing.GroupLayout facultyPanelLayout = new javax.swing.GroupLayout(facultyPanel);
        facultyPanel.setLayout(facultyPanelLayout);
        facultyPanelLayout.setHorizontalGroup(
            facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultyScrollPane)
                    .addComponent(txtFacultySearch)
                    .addGroup(facultyPanelLayout.createSequentialGroup()
                        .addComponent(btnSearchFacultyById, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchFacultyByName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchFacultyByDept, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(facultyPanelLayout.createSequentialGroup()
                        .addComponent(btnViewEditFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAssignFaculty)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshFacultyList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        facultyPanelLayout.setVerticalGroup(
            facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFacultySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchFacultyById)
                    .addComponent(btnSearchFacultyByName)
                    .addComponent(btnSearchFacultyByDept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facultyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewEditFaculty)
                    .addComponent(btnDeleteFaculty)
                    .addComponent(btnAssignFaculty)
                    .addComponent(btnRefreshFacultyList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Faculty", facultyPanel);

        btnSearchStudentById.setText("Search by ID");
        btnSearchStudentById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentByIdActionPerformed(evt);
            }
        });

        btnSearchStudentByName.setText("Search by Name");

        btnSearchStudentByDept.setText("Search by Dept");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentScrollPane.setViewportView(tblStudents);

        btnViewEditStudent.setText("View / Edit Details");

        btnDeleteStudent.setText("Delete Record");

        btnRefreshStudentList.setText("Refresh Table");

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentScrollPane)
                    .addComponent(txtStudentSearch)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addComponent(btnSearchStudentById, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchStudentByName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchStudentByDept, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addComponent(btnViewEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshStudentList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchStudentById)
                    .addComponent(btnSearchStudentByName)
                    .addComponent(btnSearchStudentByDept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewEditStudent)
                    .addComponent(btnDeleteStudent)
                    .addComponent(btnRefreshStudentList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Student", studentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchFacultyByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFacultyByIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchFacultyByIdActionPerformed

    private void btnSearchStudentByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentByIdActionPerformed
        // TODO add your handling code here:
        // --- "Search by ID" is implemented ---
        String searchId = txtStudentSearch.getText().trim();
        if (searchId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Use the findStudent method from StudentDirectory
        StudentProfile foundStudent = department.getStudentDirectory().findStudent(searchId);
        
        ArrayList<StudentProfile> searchResults = new ArrayList<>();
        if (foundStudent != null) {
            searchResults.add(foundStudent); // Found, add to list
        } 
        
        // Refresh the table using the new populate method
        populateStudentTable(searchResults); 
        
        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No student found with ID: " + searchId, "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchStudentByIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignFaculty;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteFaculty;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnRefreshFacultyList;
    private javax.swing.JButton btnRefreshStudentList;
    private javax.swing.JButton btnSearchFacultyByDept;
    private javax.swing.JButton btnSearchFacultyById;
    private javax.swing.JButton btnSearchFacultyByName;
    private javax.swing.JButton btnSearchStudentByDept;
    private javax.swing.JButton btnSearchStudentById;
    private javax.swing.JButton btnSearchStudentByName;
    private javax.swing.JButton btnViewEditFaculty;
    private javax.swing.JButton btnViewEditStudent;
    private javax.swing.JPanel facultyPanel;
    private javax.swing.JScrollPane facultyScrollPane;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JScrollPane studentScrollPane;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblFaculty;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtFacultySearch;
    private javax.swing.JTextField txtStudentSearch;
    // End of variables declaration//GEN-END:variables
}
