/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseSchedule.CourseOffer; // Import CourseOffer
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Person;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author ouyangkairui
 */
public class EditCourseOfferingJPanel extends javax.swing.JPanel {
    
    private JPanel CardSequencePanel;
    private Business business;
    private CourseOffer courseOfferToEdit; // Variable to hold the CourseOffer being edited
    private ManageCourseOfferingsJPanel manageCourseOfferingsPanel; // Reference to refresh table
    
   
    /**
     * Creates new form EditCourseOfferingJPanel
     */
    public EditCourseOfferingJPanel(Business bz, JPanel clp, ManageCourseOfferingsJPanel previousPanel, CourseOffer courseOffer) {
        initComponents();
        this.business = bz;
        this.CardSequencePanel = clp;
        this.manageCourseOfferingsPanel = previousPanel;
        this.courseOfferToEdit = courseOffer; // Store the passed CourseOffer

        populateFacultyCombo(); // Populate faculty dropdown first
        populateFields(); // Then populate fields with current data
    }
    
    
    // Method to fill the faculty dropdown
    private void populateFacultyCombo() {
        DefaultComboBoxModel<FacultyProfile> model = new DefaultComboBoxModel<>();
        Department department = business.getDepartment();
        FacultyDirectory facultyDirectory = department.getFacultyDirectory();
        ArrayList<FacultyProfile> faculties = facultyDirectory.getTeacherList();

        model.addElement(null); // Add a null option for "Unassigned"

        for (FacultyProfile faculty : faculties) {
            model.addElement(faculty); // Add the FacultyProfile object
        }
        comboFaculty.setModel(model);
        comboFaculty.setRenderer(new javax.swing.DefaultListCellRenderer() {
             @Override
             public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                 super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                 if (value instanceof FacultyProfile) {
                     FacultyProfile faculty = (FacultyProfile) value;
                     Person person = faculty.getPerson();
                     if (person != null) {
                         setText(person.getName());
                     } else {
                         setText("Unknown Faculty");
                     }
                 } else {
                     setText("Select Faculty (Optional)");
                 }
                 return this;
             }
        });
    }
    
    
    // Method to populate the form fields with data from the CourseOffer being edited
    private void populateFields() {
        if (courseOfferToEdit == null) {
            return; 
        }

        Course course = courseOfferToEdit.getSubjectCourse();
        lblCourseNumber.setText(course.getCourseNumber());
        lblCourseName.setText(course.getName());

        txtCapacity.setText(String.valueOf(courseOfferToEdit.getSeatCount()));
        txtSchedule.setText(courseOfferToEdit.getScheduleTime());

        txtRoom.setText("To be Added"); 

        // Select the currently assigned faculty in the dropdown
        FacultyProfile currentFaculty = courseOfferToEdit.getFacultyProfile();
        comboFaculty.setSelectedItem(currentFaculty); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSchedule = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboFaculty = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCourseNumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();

        jLabel6.setText("Room:");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Edit Course Offering");

        btnSave.setText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel3.setText("Assign Faculty:");

        jLabel4.setText("Capacity (Seats):");

        jLabel5.setText("Schedule:");

        jLabel2.setText("Course Number:");

        jLabel8.setText("Course Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(149, 149, 149)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRoom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSchedule, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCapacity, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboFaculty, javax.swing.GroupLayout.Alignment.LEADING, 0, 129, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnCancel)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // --- 1. Get User Input ---
        FacultyProfile selectedFaculty = (FacultyProfile) comboFaculty.getSelectedItem();
        String capacityStr = txtCapacity.getText().trim();
        String scheduleStr = txtSchedule.getText().trim();
        String roomStr = txtRoom.getText().trim();

        // --- 2. Input Validation ---
        int capacity;
        try {
            capacity = Integer.parseInt(capacityStr);
            if (capacity <= 0) {
                JOptionPane.showMessageDialog(this, "Capacity must be a positive number.", "Input Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for capacity.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Add more validation if needed
         if (scheduleStr.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Please enter a schedule.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
         if (roomStr.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Please enter a room.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }


        // --- 3. Update Course Offering Object ---
        // The object 'courseOfferToEdit' already holds the CourseOffer we want to modify

        // Update Faculty
        courseOfferToEdit.assignFaculty(selectedFaculty); // assignFaculty handles null internally perhaps, or check here

        // Update Capacity 
        if (capacity != courseOfferToEdit.getSeatCount()) {
             courseOfferToEdit.getSeatList().clear(); // Clear old seats first
             courseOfferToEdit.generatSeats(capacity);
             System.out.println("Warning: Seats regenerated, existing assignments might be lost."); // Add a log or user warning
        }


        // Update Schedule
        courseOfferToEdit.setScheduleTime(scheduleStr);

        // Update Room (Requires setRoom in CourseOffer.java)
        // courseOfferToEdit.setRoom(roomStr);

        // --- 4. Confirmation and Navigation ---
        JOptionPane.showMessageDialog(this, "Course Offering updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Refresh the table in the previous panel
        manageCourseOfferingsPanel.populateTable();

        // Go back to the previous panel
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        // Remove this panel
        CardSequencePanel.remove(this);
        // Show the previous panel
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<FacultyProfile> comboFaculty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseNumber;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtSchedule;
    // End of variables declaration//GEN-END:variables
}
