/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import Business.UserAccounts.UserAccount; 
import info5100.university.example.Persona.Person;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author ouyangkairui
 */
public class ManageRegistrarProfileJPanel extends javax.swing.JPanel {
    
    private JPanel CardSequencePanel;
    private Business business;
    private Person registrarPerson; // Variable to hold the Registrar's Person object
    
    /**
     * Creates new form ManageRegistrarProfileJPanel
     */
    public ManageRegistrarProfileJPanel(Business bz, JPanel clp, UserAccount registrarAccount) {
        initComponents();
        this.business = bz;
        this.CardSequencePanel = clp;

        // Get the Person object from the UserAccount
        if (registrarAccount != null) {
            this.registrarPerson = registrarAccount.getAssociatedPerson();
        } else {
             // Handle error: should not happen if navigation is correct
             System.err.println("Error: Registrar UserAccount is null in ManageRegistrarProfileJPanel.");
             this.registrarPerson = null; // Set to null to avoid NullPointerException later
        }

        populateFields(); 
    }
    
    
    private void populateFields() {
        if (registrarPerson == null) {
             // Optionally disable fields or show an error message
             txtName.setEnabled(false);
             txtContactInfo.setEnabled(false);
             txtOfficeHours.setEnabled(false);
             btnSave.setEnabled(false);
             lblUserId.setText("Error: User not found");
             return;
        }

        txtName.setText(registrarPerson.getName());
        lblUserId.setText(registrarPerson.getPersonId()); // Display ID (read-only)

        // Use the new getters from Person.java
        txtContactInfo.setText(registrarPerson.getContactInfo() != null ? registrarPerson.getContactInfo() : "");
        txtOfficeHours.setText(registrarPerson.getOfficeHours() != null ? registrarPerson.getOfficeHours() : "");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtContactInfo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOfficeHours = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Manage My Profile");

        jLabel2.setText("Name:");

        jLabel3.setText("User ID:");

        jLabel4.setText("Contact Info:");

        jLabel5.setText("Office Hours:");

        btnSave.setText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOfficeHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUserId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContactInfo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btnSave)
                        .addGap(95, 95, 95)
                        .addComponent(btnBack)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOfficeHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (registrarPerson == null) {
        JOptionPane.showMessageDialog(this, "Cannot save. User profile not loaded correctly.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // --- 1. Get User Input ---
    String newName = txtName.getText().trim();
    String newContactInfo = txtContactInfo.getText().trim();
    String newOfficeHours = txtOfficeHours.getText().trim();

    // --- 2. Input Validation ---
    if (newName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Name cannot be empty.", "Input Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
    // Add more validation if needed (e.g., format for contact info or office hours)

    // --- 3. Update Person Object ---
    registrarPerson.setName(newName);
    registrarPerson.setContactInfo(newContactInfo); 
    registrarPerson.setOfficeHours(newOfficeHours); 

    // --- 4. Confirmation ---
    JOptionPane.showMessageDialog(this, "Profile updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

    // Optional: Navigate back after saving
    // CardSequencePanel.remove(this);
    // java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
    // layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JTextField txtContactInfo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOfficeHours;
    // End of variables declaration//GEN-END:variables
}
