/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Person; 
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.Persona.Faculty.FacultyProfile; 
import info5100.university.example.CourseSchedule.Seat;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.Persona.Transcript;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; 


/**
 *
 * @author ouyangkairui
 */
public class ManageStudentRegistrationJPanel extends javax.swing.JPanel {
    
    private JPanel CardSequencePanel;
    private Business business;
    
    /**
     * Creates new form ManageStudentRegistrationJPanel
     */
    public ManageStudentRegistrationJPanel(Business bz, JPanel clp) {
        initComponents();
        this.business = bz;
        this.CardSequencePanel = clp;

        populateStudentTable();
        populateCourseOfferingTable();
    }
    
    
    private void populateStudentTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0); // Clear existing data

        Department department = business.getDepartment();
        StudentDirectory studentDirectory = department.getStudentDirectory();

        // Check if studentDirectory or studentlist is null before iterating
        if (studentDirectory != null && studentDirectory.getStudentlist() != null) {
            for (StudentProfile student : studentDirectory.getStudentlist()) {
                Person person = student.getPerson();
                if (person != null) {
                    Object[] row = new Object[2]; // Adjust size based on columns
                    row[0] = person.getPersonId(); // Column 0: Student ID
                    row[1] = person.getName();    // Column 1: Student Name
                    model.addRow(row);
                }
            }
        } else {
             System.err.println("Student directory or list is null.");
             // Optionally show an error message to the user
        }
    }
    
    private void populateCourseOfferingTable() {
    DefaultTableModel model = (DefaultTableModel) tblCourseOfferings.getModel();
        model.setRowCount(0); // Clear existing data

        Department department = business.getDepartment();
        CourseSchedule courseSchedule = department.getCourseSchedule("Fall 2025"); // Assuming Fall 2025

        if (courseSchedule == null) {
            System.err.println("Course schedule for Fall 2025 not found.");
            return;
        }

        ArrayList<CourseOffer> courseOffers = courseSchedule.getSchedule();

        for (CourseOffer co : courseOffers) {
            FacultyProfile faculty = co.getFacultyProfile();
            String facultyName = (faculty != null && faculty.getPerson() != null) ? faculty.getPerson().getName() : "Unassigned";

            Object[] row = new Object[4]; // Adjust size based on columns
            row[0] = co.getCourseNumber();                             // Course Number
            row[1] = co.getSubjectCourse().getName();                 // Course Name
            row[2] = facultyName;                                     // Faculty
            row[3] = co.getEnrolledCount() + "/" + co.getSeatCount(); // Enrolled/Capacity
            model.addRow(row);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourseOfferings = new javax.swing.JTable();
        btnEnroll = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Manage Student Registration");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student ID", "Student Name"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        jLabel2.setText("Select Student:");

        jLabel3.setText("Select Course Offering (Fall 2025):");

        tblCourseOfferings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Faculty", "Enrolled/Capacity"
            }
        ));
        jScrollPane2.setViewportView(tblCourseOfferings);

        btnEnroll.setText("Enroll Student");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnDrop.setText(" Drop Student");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnroll)
                                .addGap(63, 63, 63)
                                .addComponent(btnDrop)
                                .addGap(78, 78, 78)
                                .addComponent(btnBack)))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnroll)
                    .addComponent(btnDrop)
                    .addComponent(btnBack))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        // --- 1. Get Selected Student ---
        int selectedStudentRow = tblStudents.getSelectedRow();
        if (selectedStudentRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Assuming Student ID is in column 0
        String selectedStudentId = (String) tblStudents.getValueAt(selectedStudentRow, 0);
        Department department = business.getDepartment();
        StudentProfile selectedStudent = department.getStudentDirectory().findStudent(selectedStudentId);
        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Could not find the selected student profile.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 2. Get Selected Course Offering ---
        int selectedCourseRow = tblCourseOfferings.getSelectedRow();
        if (selectedCourseRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course offering.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Assuming Course Number is in column 0
        String selectedCourseNumber = (String) tblCourseOfferings.getValueAt(selectedCourseRow, 0);
        CourseSchedule courseSchedule = department.getCourseSchedule("Fall 2025"); // Assuming Fall 2025
        if (courseSchedule == null) {
            JOptionPane.showMessageDialog(this, "Course schedule not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CourseOffer selectedCourseOffer = courseSchedule.getCourseOfferByNumber(selectedCourseNumber);
        if (selectedCourseOffer == null) {
            JOptionPane.showMessageDialog(this, "Could not find the selected course offering.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 3. Perform Validations ---

        // Check if course is full
        if (selectedCourseOffer.getEmptySeat() == null) {
            JOptionPane.showMessageDialog(this, "Cannot enroll: Course '" + selectedCourseNumber + "' is full.", "Enrollment Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get student's current courseload for the semester
        // Assuming Transcript has a method to get or create CourseLoad for a semester
        Transcript transcript = selectedStudent.getTranscript();
        CourseLoad currentLoad = transcript.getCourseLoadBySemester("Fall 2025");
        // If student has no load for this semester yet, create one
        if (currentLoad == null) {
            currentLoad = transcript.newCourseLoad("Fall 2025");
        }

        // Check if student is already enrolled in this course
        ArrayList<SeatAssignment> currentAssignments = currentLoad.getSeatAssignments();
        for (SeatAssignment sa : currentAssignments) {
            if (sa.getCourseOffer() == selectedCourseOffer) {
                 JOptionPane.showMessageDialog(this, "Student is already enrolled in " + selectedCourseNumber + ".", "Enrollment Error", JOptionPane.WARNING_MESSAGE);
                 return;
            }
        }

        // Check credit hour limit (8 credits as per requirements )
        int currentCredits = 0;
        for (SeatAssignment sa : currentAssignments) {
            currentCredits += sa.getCreditHours();
        }
        int courseCredits = selectedCourseOffer.getCreditHours();
        if (currentCredits + courseCredits > 8) {
            JOptionPane.showMessageDialog(this, "Cannot enroll: Exceeds maximum credit hours (8) for the semester. Current credits: " + currentCredits, "Enrollment Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- 4. Enroll Student ---
        // The assignEmptySeat method handles finding a seat and creating the SeatAssignment
        SeatAssignment newAssignment = selectedCourseOffer.assignEmptySeat(currentLoad);

        // --- 5. Feedback and Refresh ---
        if (newAssignment != null) {
            JOptionPane.showMessageDialog(this, "Student '" + selectedStudent.getPerson().getName() + "' successfully enrolled in " + selectedCourseNumber + ".", "Enrollment Successful", JOptionPane.INFORMATION_MESSAGE);
            // Refresh the course offering table to show updated enrollment count
            populateCourseOfferingTable();
        } else {
            // This case might occur if getEmptySeat() check fails due to race condition, though unlikely here.
            JOptionPane.showMessageDialog(this, "Failed to enroll student. The course might have become full.", "Enrollment Error", JOptionPane.ERROR_MESSAGE);
            populateCourseOfferingTable(); // Refresh anyway
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
        // --- 1. Get Selected Student ---
        int selectedStudentRow = tblStudents.getSelectedRow();
        if (selectedStudentRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String selectedStudentId = (String) tblStudents.getValueAt(selectedStudentRow, 0);
        Department department = business.getDepartment();
        StudentProfile selectedStudent = department.getStudentDirectory().findStudent(selectedStudentId);
        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Could not find the selected student profile.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 2. Get Selected Course Offering ---
        int selectedCourseRow = tblCourseOfferings.getSelectedRow();
        if (selectedCourseRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select the course offering to drop the student from.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String selectedCourseNumber = (String) tblCourseOfferings.getValueAt(selectedCourseRow, 0);
        CourseSchedule courseSchedule = department.getCourseSchedule("Fall 2025"); // Assuming Fall 2025
        if (courseSchedule == null) {
            JOptionPane.showMessageDialog(this, "Course schedule not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CourseOffer selectedCourseOffer = courseSchedule.getCourseOfferByNumber(selectedCourseNumber);
        if (selectedCourseOffer == null) {
            JOptionPane.showMessageDialog(this, "Could not find the selected course offering.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 3. Find the Student's Seat Assignment for this Course ---
        Transcript transcript = selectedStudent.getTranscript();
        CourseLoad currentLoad = transcript.getCourseLoadBySemester("Fall 2025");
        SeatAssignment assignmentToDrop = null;

        if (currentLoad != null) {
            // Iterate through the student's assignments in the current semester
            for (SeatAssignment sa : currentLoad.getSeatAssignments()) {
                // Check if the assignment belongs to the selected CourseOffer
                if (sa.getCourseOffer() == selectedCourseOffer) {
                    assignmentToDrop = sa;
                    break; // Found the assignment
                }
            }
        }

        // --- 4. Validation: Check if student is actually enrolled ---
        if (assignmentToDrop == null) {
            JOptionPane.showMessageDialog(this, "Student '" + selectedStudent.getPerson().getName() + "' is not enrolled in " + selectedCourseNumber + ".", "Drop Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- 5. Confirmation Dialog ---
         int confirmation = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to drop student '" + selectedStudent.getPerson().getName() + "' from " + selectedCourseNumber + "?",
            "Confirm Drop",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        // --- 6. Drop Student if Confirmed ---
        if (confirmation == JOptionPane.YES_OPTION) {
            // Remove the SeatAssignment from the student's CourseLoad
            boolean removedFromLoad = currentLoad.getSeatAssignments().remove(assignmentToDrop);

            // Mark the Seat in the CourseOffer as unoccupied
            Seat seat = assignmentToDrop.getSeat(); // Get the associated Seat
            boolean seatFreed = false;
            if (seat != null) {
                seat.unassignSeat(); // Call the new method to properly unassign
                seatFreed = !seat.isOccupied();
            }

            // --- 7. Feedback and Refresh ---
            if (removedFromLoad && seatFreed) {
                JOptionPane.showMessageDialog(this, "Student dropped successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Refresh the course offering table
                populateCourseOfferingTable();
            } else {
                 JOptionPane.showMessageDialog(this, "Failed to drop student. Could not update records.", "Error", JOptionPane.ERROR_MESSAGE);
                 // Refresh tables anyway to ensure consistency
                 populateCourseOfferingTable();
            }
        }
        // If user chose NO, do nothing.
    }//GEN-LAST:event_btnDropActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCourseOfferings;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables
}
