/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.*;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import info5100.university.example.Department.Department;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.CourseOffer; 
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.CourseSchedule.CourseOffer; 
import java.util.ArrayList;
import javax.swing.JOptionPane; 
import java.util.ArrayList;

/**
 *
 * @author ouyangkairui
 */
public class ManageCourseOfferingsJPanel extends javax.swing.JPanel {
    
    private JPanel CardSequencePanel;
    private Business business;
    
    /**
     * Creates new form ManageCourseOfferingsJPanel
     */
    public ManageCourseOfferingsJPanel(Business bz, JPanel clp) {
        initComponents();
        this.business = bz;
        this.CardSequencePanel = clp;
    }

public void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblCourseOfferings.getModel();
    model.setRowCount(0);

    //get department from business
    Department department = business.getDepartment();
    CourseSchedule courseSchedule = department.getCourseSchedule("Fall 2025");

    // check exist
    if (courseSchedule == null) {
        System.out.println("Error: Can't find course schedule!");
        return; 
    }

    // Get course offer list
    ArrayList<CourseOffer> courseOffers = courseSchedule.getSchedule();

    
    for (CourseOffer co : courseOffers) {
        String courseNumber = co.getCourseNumber(); 
        String courseName = co.getSubjectCourse().getName(); 

        // get faculty
        FacultyProfile faculty = co.getFacultyProfile();
        String facultyName = (faculty != null && faculty.getPerson() != null) ? faculty.getPerson().getName() : "Not assigned.";

        
        int capacity = co.getSeatCount(); 
        int enrolled = co.getEnrolledCount(); 
        
        
        String schedule = co.getScheduleTime(); 

        
        String room = "undetermined";

        
        Object[] row = new Object[7]; 
        row[0] = courseNumber;
        row[1] = courseName;
        row[2] = facultyName;
        row[3] = capacity;
        row[4] = enrolled;
        row[5] = schedule;
        row[6] = room;

        
        model.addRow(row);
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseOfferings = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnViewEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblCourseOfferings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Faculty", "Capacity", "Enrolled", "Schedule", "Room"
            }
        ));
        jScrollPane1.setViewportView(tblCourseOfferings);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnViewEdit.setText("View/Edit");
        btnViewEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Course offering management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnCreate)
                        .addGap(68, 68, 68)
                        .addComponent(btnViewEdit)
                        .addGap(73, 73, 73)
                        .addComponent(btnDelete)
                        .addGap(43, 43, 43)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnViewEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnBack))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        // Create instance of the new panel, passing business, card panel, and 'this' (for refreshing later)
        CreateCourseOfferingJPanel createPanel = new CreateCourseOfferingJPanel(business, CardSequencePanel, this); // Pass 'this'

        // Add the new panel to the card sequence panel
        CardSequencePanel.add("CreateCourseOffering", createPanel);

        // Switch to the new panel
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditActionPerformed
        // TODO add your handling code here:
        // --- 1. Get Selected Row ---
        int selectedRowIndex = tblCourseOfferings.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course offering to view/edit.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- 2. Get CourseOffer Object ---
        // We need the Course Number from the selected row to find the CourseOffer
        DefaultTableModel model = (DefaultTableModel) tblCourseOfferings.getModel();
        String selectedCourseNumber = (String) model.getValueAt(selectedRowIndex, 0); // Assuming Course Number is in column 0

        Department department = business.getDepartment();
        CourseSchedule courseSchedule = department.getCourseSchedule("Fall 2025"); // Assuming Fall 2025
        if (courseSchedule == null) {
             JOptionPane.showMessageDialog(this, "Course schedule not found.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }

        CourseOffer selectedCourseOffer = courseSchedule.getCourseOfferByNumber(selectedCourseNumber);
        if (selectedCourseOffer == null) {
            JOptionPane.showMessageDialog(this, "Could not find the selected course offering.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 3. Navigate to Edit Panel ---
        EditCourseOfferingJPanel editPanel = new EditCourseOfferingJPanel(business, CardSequencePanel, this, selectedCourseOffer); // Pass the selected CourseOffer

        CardSequencePanel.add("EditCourseOffering", editPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnViewEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        // --- 1. Get Selected Row ---
        int selectedRowIndex = tblCourseOfferings.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course offering to delete.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- 2. Get CourseOffer Object ---
        DefaultTableModel model = (DefaultTableModel) tblCourseOfferings.getModel();
        String selectedCourseNumber = (String) model.getValueAt(selectedRowIndex, 0); // Assuming Course Number is in column 0

        Department department = business.getDepartment();
        CourseSchedule courseSchedule = department.getCourseSchedule("Fall 2025"); // Assuming Fall 2025
        if (courseSchedule == null) {
             JOptionPane.showMessageDialog(this, "Course schedule not found.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }

        CourseOffer courseOfferToDelete = courseSchedule.getCourseOfferByNumber(selectedCourseNumber);
        if (courseOfferToDelete == null) {
            JOptionPane.showMessageDialog(this, "Could not find the selected course offering.", "Error", JOptionPane.ERROR_MESSAGE);
            // It might have been deleted already, refresh table just in case
            populateTable();
            return;
        }

        // --- 3. Confirmation Dialog ---
        int confirmation = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete the offering for " + selectedCourseNumber + "?\nThis action cannot be undone.",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        // --- 4. Delete if Confirmed ---
        if (confirmation == JOptionPane.YES_OPTION) {
            // Remove the CourseOffer from the schedule's list
            // We need to access the underlying ArrayList in CourseSchedule
            ArrayList<CourseOffer> scheduleList = courseSchedule.getSchedule(); // Assuming getSchedule() returns the ArrayList
            boolean removed = scheduleList.remove(courseOfferToDelete);

            if (removed) {
                JOptionPane.showMessageDialog(this, "Course Offering deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Refresh the table to show the updated list
                populateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the course offering.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        // If user chose NO, do nothing.
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourseOfferings;
    // End of variables declaration//GEN-END:variables
}
