/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.*;
import javax.swing.JPanel;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import info5100.university.example.Persona.Person;
import UserInterface.WorkAreas.RegistrarRole.ManageCourseOfferingsJPanel;
import UserInterface.WorkAreas.RegistrarRole.ManageRegistrarProfileJPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author ouyangkairui
 */
public class RegistrarWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel CardSequencePanel;
    private Business business;
    // private RegistrarProfile registrarProfile;
    
    /**
     * Creates new form RegistrarWorkAreaJPanel
     */
    public RegistrarWorkAreaJPanel(Business bz, JPanel clp) {
        initComponents();
        this.business = bz;
        this.CardSequencePanel = clp;
        // this.registrarProfile = rp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCourseOfferings = new javax.swing.JButton();
        btnManageStudentReg = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnTuitionFinancial = new javax.swing.JButton();
        btnReportingAnalytics = new javax.swing.JButton();

        btnManageCourseOfferings.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageCourseOfferings.setText("Course Offering Management");
        btnManageCourseOfferings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseOfferingsActionPerformed(evt);
            }
        });

        btnManageStudentReg.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageStudentReg.setText("Student Registration");
        btnManageStudentReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentRegActionPerformed(evt);
            }
        });

        btnManageProfile.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageProfile.setText("Manage own profile");
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnTuitionFinancial.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnTuitionFinancial.setText("Tuition & Financial Reconciliation");

        btnReportingAnalytics.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnReportingAnalytics.setText("Reporting & Analytics");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnManageProfile)
                .addGap(327, 327, 327))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnManageCourseOfferings)
                        .addGap(126, 126, 126)
                        .addComponent(btnManageStudentReg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnTuitionFinancial)
                        .addGap(128, 128, 128)
                        .addComponent(btnReportingAnalytics)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnManageCourseOfferings)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnManageStudentReg)
                        .addGap(77, 77, 77)))
                .addComponent(btnManageProfile)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTuitionFinancial)
                    .addComponent(btnReportingAnalytics))
                .addGap(164, 164, 164))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStudentRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentRegActionPerformed
        // TODO add your handling code here:
        ManageStudentRegistrationJPanel manageStudentRegPanel = new ManageStudentRegistrationJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageStudentRegistration", manageStudentRegPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageStudentRegActionPerformed


    private void btnManageCourseOfferingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseOfferingsActionPerformed
        // TODO add your handling code here:
        ManageCourseOfferingsJPanel manageCourseOfferingsPanel = new ManageCourseOfferingsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageCourseOfferings", manageCourseOfferingsPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageCourseOfferingsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        // --- Find the Registrar User Account (Simplified Approach) ---
        UserAccountDirectory uad = business.getUserAccountDirectory();
        UserAccount registrarAccount = uad.findUserAccount("registrar"); // Find by username used in ConfigureABusiness

        if (registrarAccount == null) {
             JOptionPane.showMessageDialog(this, "Could not find Registrar account.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
         // Alternative if finding by Person ID R001:
         // Person registrarPerson = business.getDepartment().getPersonDirectory().findPerson("R001");
         // UserAccount registrarAccount = uad.findUserAccountByPerson(registrarPerson); // Need to add findUserAccountByPerson to UserAccountDirectory

        // --- Navigate ---
        ManageRegistrarProfileJPanel manageProfilePanel = new ManageRegistrarProfileJPanel(business, CardSequencePanel, registrarAccount); // Pass the found account
        CardSequencePanel.add("ManageRegistrarProfile", manageProfilePanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageProfileActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourseOfferings;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnManageStudentReg;
    private javax.swing.JButton btnReportingAnalytics;
    private javax.swing.JButton btnTuitionFinancial;
    // End of variables declaration//GEN-END:variables
}
