/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import info5100.university.example.Department.Department;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Persona.Transcript; 
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.CourseSchedule.CourseLoad; 
import info5100.university.example.CourseSchedule.SeatAssignment; 
import java.util.ArrayList;
import java.util.HashMap; 
import java.util.Map; 
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ouyangkairui
 */
public class ReportingAnalyticsJPanel extends javax.swing.JPanel {
    
    private JPanel CardSequencePanel;
    private Business business;
    
    /**
     * Creates new form ReportingAnalyticsJPanel
     */
    public ReportingAnalyticsJPanel(Business bz, JPanel clp) {
        initComponents();
        this.business = bz;
        this.CardSequencePanel = clp;

        // Initialize combo box items
        comboReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Select Report",
            "Enrollment by Course (Fall 2025)", // Specify semester for clarity
            "GPA Distribution (Overall)" // Specify scope for clarity
        }));

        // Initially clear the table
        clearTable();
    }
    
    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tblReportResults.getModel();
        model.setRowCount(0);
        model.setColumnCount(0); // Remove existing columns
        // Add a default placeholder column
        model.addColumn("Select a report type and click Generate");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboReportType = new javax.swing.JComboBox<>();
        btnGenerate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportResults = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Reporting & Analytics");

        jLabel2.setText("Select Report Type:");

        comboReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Report", "Enrollment by Course", "GPA Distribution", " " }));

        btnGenerate.setText("Generate Report");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        tblReportResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReportResults);

        jLabel3.setText("Report Results:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(btnGenerate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addComponent(comboReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(btnBack)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerate)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        String selectedReport = (String) comboReportType.getSelectedItem();

        if (selectedReport == null || selectedReport.equals("Select Report")) {
            JOptionPane.showMessageDialog(this, "Please select a report type.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            clearTable(); // Clear table if no report selected
            return;
        }

        // Call specific methods based on selection
        if (selectedReport.startsWith("Enrollment by Course")) {
            generateEnrollmentReport();
        } else if (selectedReport.startsWith("GPA Distribution")) {
            generateGpaDistributionReport();
        } else {
            clearTable(); // Clear table for unknown selection
        }
    }//GEN-LAST:event_btnGenerateActionPerformed
    
    private void generateEnrollmentReport() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Course Number", "Course Name", "Faculty", "Enrollment", "Capacity"}); // Define columns

        Department department = business.getDepartment();
        // Assuming Fall 2025 semester for this report
        CourseSchedule courseSchedule = department.getCourseSchedule("Fall 2025");

        if (courseSchedule == null) {
            JOptionPane.showMessageDialog(this, "Course schedule for Fall 2025 not found.", "Error", JOptionPane.ERROR_MESSAGE);
            tblReportResults.setModel(model); // Set empty model
            return;
        }

        ArrayList<CourseOffer> courseOffers = courseSchedule.getSchedule();

        if (courseOffers.isEmpty()) {
             model.addRow(new Object[]{"No course offerings found for Fall 2025", "", "", "", ""});
        } else {
            for (CourseOffer co : courseOffers) {
                FacultyProfile faculty = co.getFacultyProfile();
                String facultyName = (faculty != null && faculty.getPerson() != null) ? faculty.getPerson().getName() : "Unassigned";

                Object[] row = new Object[5];
                row[0] = co.getCourseNumber();
                row[1] = co.getSubjectCourse().getName();
                row[2] = facultyName;
                row[3] = co.getEnrolledCount();
                row[4] = co.getSeatCount();
                model.addRow(row);
            }
        }
        tblReportResults.setModel(model); // Display the data
    }
    
    private void generateGpaDistributionReport() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"GPA Range", "Number of Students"}); // Define columns

        Department department = business.getDepartment();
        StudentDirectory studentDirectory = department.getStudentDirectory();

        if (studentDirectory == null || studentDirectory.getStudentlist() == null) {
             JOptionPane.showMessageDialog(this, "Cannot generate report: Student data unavailable.", "Error", JOptionPane.ERROR_MESSAGE);
             tblReportResults.setModel(model); // Set empty model
             return;
        }

        ArrayList<StudentProfile> studentList = studentDirectory.getStudentlist();

        // Count students in different GPA ranges
        int count40 = 0; // GPA = 4.0
        int count35_39 = 0; // 3.5 <= GPA < 4.0
        int count30_34 = 0; // 3.0 <= GPA < 3.5
        int countBelow30 = 0; // GPA < 3.0

        if (studentList.isEmpty()) {
             model.addRow(new Object[]{"No student data available", 0});
        } else {
            for (StudentProfile student : studentList) {
                Transcript transcript = student.getTranscript();
                // Assuming calculateOverallGPA() is added to Transcript.java
                double gpa = transcript.calculateOverallGPA();

                // Categorize GPA
                if (gpa == 4.0) {
                    count40++;
                } else if (gpa >= 3.5) {
                    count35_39++;
                } else if (gpa >= 3.0) {
                    count30_34++;
                } else { // Assuming GPA cannot be negative
                    countBelow30++;
                }
            }

            // Add rows to the model
            model.addRow(new Object[]{"GPA = 4.0", count40});
            model.addRow(new Object[]{"3.5 <= GPA < 4.0", count35_39});
            model.addRow(new Object[]{"3.0 <= GPA < 3.5", count30_34});
            model.addRow(new Object[]{"GPA < 3.0", countBelow30});
        }

        tblReportResults.setModel(model); // Display the data
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JComboBox<String> comboReportType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReportResults;
    // End of variables declaration//GEN-END:variables
}
