/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.SeatAssignment;
import java.util.ArrayList;
import java.util.HashMap; 
import java.util.Set; 
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ouyangkairui
 */
public class TuitionFinancialJPanel extends javax.swing.JPanel {
    
    private JPanel CardSequencePanel;
    private Business business;
    
    /**
     * Creates new form TuitionFinancialJPanel
     */
    public TuitionFinancialJPanel(Business bz, JPanel clp) {
        initComponents();
        this.business = bz;
        this.CardSequencePanel = clp;

        populateStudentTuitionTable();
        populateSemesterCombo(); 
    }
    
    private void populateStudentTuitionTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudentTuition.getModel();
        model.setRowCount(0); // Clear existing data

        Department department = business.getDepartment();
        StudentDirectory studentDirectory = department.getStudentDirectory();

        if (studentDirectory != null && studentDirectory.getStudentlist() != null) {
            for (StudentProfile student : studentDirectory.getStudentlist()) {
                Person person = student.getPerson();
                if (person != null) {
                    Object[] row = new Object[3]; // Student ID, Name, Balance
                    row[0] = person.getPersonId();
                    row[1] = person.getName();
                    row[2] = String.format("%.2f", student.getTuitionBalance()); // Format balance to 2 decimal places
                    model.addRow(row);
                }
            }
        } else {
             System.err.println("Student directory or list is null in TuitionFinancialJPanel.");
        }
    }
    
    private void populateSemesterCombo() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        Department department = business.getDepartment();

        // We need a way to get all semester names from the Department or its master catalog
        // Assuming Department has a method like getAvailableSemesters() or similar
        // Let's modify Department.java first.

        // --- Modification needed in Department.java ---
        // Add this method to Department.java:
        /*
        public Set<String> getAvailableSemesters() {
            // mastercoursecatalog is HashMap<String, CourseSchedule>
            if (mastercoursecatalog == null) {
                return new HashSet<>(); // Return empty set if null
            }
            return mastercoursecatalog.keySet();
        }
        */
        // Ensure HashMap and Set are imported in Department.java

        Set<String> semesters = department.getAvailableSemesters(); // Call the new method

        model.addElement("Select Semester"); // Add a default prompt
        for (String semester : semesters) {
            model.addElement(semester);
        }
        comboSemester.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentTuition = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboSemester = new javax.swing.JComboBox<>();
        btnGenerateReport = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaReport = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Tuition & inalcial Reconciliation");

        tblStudentTuition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Tuition Balance($)"
            }
        ));
        jScrollPane1.setViewportView(tblStudentTuition);

        jLabel2.setText("Student Tuition Status (All Students)");

        jLabel3.setText("Generate Semester Finalcial Report:");

        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        txtAreaReport.setColumns(20);
        txtAreaReport.setRows(5);
        jScrollPane3.setViewportView(txtAreaReport);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(btnGenerateReport))
                .addGap(41, 41, 41)
                .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(252, 252, 252)
                            .addComponent(jLabel2))))
                .addGap(0, 198, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerateReport)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        // TODO add your handling code here:
        // --- 1. Get Selected Semester ---
        String selectedSemester = (String) comboSemester.getSelectedItem();

        // --- 2. Validate Selection ---
        if (selectedSemester == null || selectedSemester.equals("Select Semester")) {
            JOptionPane.showMessageDialog(this, "Please select a semester to generate the report.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- 3. Initialize Calculation Variables ---
        double totalBilledForSemester = 0.0;
        double totalUnpaidBalance = 0.0;

        // --- 4. Get Student Data ---
        Department department = business.getDepartment();
        StudentDirectory studentDirectory = department.getStudentDirectory();

        // Check if student directory and list are valid
        if (studentDirectory == null || studentDirectory.getStudentlist() == null) {
            JOptionPane.showMessageDialog(this, "Cannot generate report: Student data is unavailable.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ArrayList<StudentProfile> studentList = studentDirectory.getStudentlist();

        // --- 5. Iterate Through Students and Calculate ---
        for (StudentProfile student : studentList) {
            // Get student's course load for the selected semester
            CourseLoad cl = student.getCourseLoadBySemester(selectedSemester);

            if (cl != null) {
                // Calculate tuition billed for this student in this semester
                for (SeatAssignment sa : cl.getSeatAssignments()) {
                    totalBilledForSemester += sa.getAssociatedCourse().getCoursePrice();
                }
            }

            // Sum up positive balances (unpaid amounts) across all students
            if (student.getTuitionBalance() > 0) {
                totalUnpaidBalance += student.getTuitionBalance();
            }
        }

        // --- 6. Calculate Total Collected ---
        // Simple calculation: Total Billed - Total Currently Unpaid
        double totalCollectedForSemester = totalBilledForSemester - totalUnpaidBalance;
        // Ensure collected doesn't go negative if balances include past debts/credits
        if (totalCollectedForSemester < 0) {
             totalCollectedForSemester = 0; // Or adjust logic based on how balance is truly managed
        }


        // --- 7. Format the Report ---
        StringBuilder reportText = new StringBuilder();
        reportText.append("Financial Report for Semester: ").append(selectedSemester).append("\n");
        reportText.append("=============================================\n\n");
        reportText.append(String.format("Total Tuition Billed: $%,.2f\n", totalBilledForSemester));
        reportText.append(String.format("Total Unpaid Tuition (Current Balance > 0): $%,.2f\n", totalUnpaidBalance));
        reportText.append(String.format("Estimated Total Tuition Collected: $%,.2f\n", totalCollectedForSemester));
        reportText.append("\n");

        // Per-Department Breakdown (Placeholder - Requires Model Enhancement)
        reportText.append("Per-Department Revenue Breakdown:\n");
        reportText.append("  (Note: Requires linking students or courses to departments in the data model)\n");

        // --- 8. Display the Report ---
        txtAreaReport.setText(reportText.toString());
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JComboBox<String> comboSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblStudentTuition;
    private javax.swing.JTextArea txtAreaReport;
    // End of variables declaration//GEN-END:variables
}
