/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import UserInterface.WorkAreas.FacultyRole.ManageCoursesJPanel;
import UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    FacultyProfile facultyProfile;
    /**
     * Creates new form UnitRiskWorkArea
     */

    public FacultyWorkAreaJPanel(Business b, FacultyProfile fp, JPanel clp) {

        business = b;
        this.facultyProfile = fp;
        this.business = business; 
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngCourses = new javax.swing.JButton();
        btnStudentsProfiles = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnPerformance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTuition = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnMngCourses.setBackground(new java.awt.Color(102, 153, 255));
        btnMngCourses.setFont(getFont());
        btnMngCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnMngCourses.setText(" Manage Courses");
        btnMngCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngCourses.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngCourses.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMngCourses.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMngCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngCoursesIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnStudentsProfiles.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentsProfiles.setFont(getFont());
        btnStudentsProfiles.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentsProfiles.setText("Manage Students Profiles");
        btnStudentsProfiles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentsProfiles.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStudentsProfiles.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentsProfiles.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentsProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsProfilesActionPerformed(evt);
            }
        });

        btnMyProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnMyProfile.setFont(getFont());
        btnMyProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProfile.setText("My Profile");
        btnMyProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnMyProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMyProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerformance.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformance.setFont(getFont());
        btnPerformance.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformance.setText("Performance Reports");
        btnPerformance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformance.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformance.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformance.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Faculty Profie");

        btnTuition.setBackground(new java.awt.Color(102, 153, 255));
        btnTuition.setFont(getFont());
        btnTuition.setForeground(new java.awt.Color(255, 255, 255));
        btnTuition.setText("Tuition");
        btnTuition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTuition.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTuition.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTuition.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnMngCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(btnStudentsProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMngCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentsProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngCoursesIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngCoursesIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
    ManageCoursesJPanel panel = new ManageCoursesJPanel(business, facultyProfile, CardSequencePanel);
    CardSequencePanel.add("ManageCourses", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnMngCoursesIdentifyResourceAssetsActionPerformed

    private void btnStudentsProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsProfilesActionPerformed
        // TODO add your handling code here:
        ManageStudentsJPanel panel = new ManageStudentsJPanel(facultyProfile);
        CardSequencePanel.add("ManageStudentsJPanel", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
  
    }//GEN-LAST:event_btnStudentsProfilesActionPerformed

    private void btnMyProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileIdentifyEventsActionPerformed
       ManageProfileJPanel panel = new ManageProfileJPanel(facultyProfile, CardSequencePanel);
       CardSequencePanel.add("ManageProfileJPanel", panel);
       ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnMyProfileIdentifyEventsActionPerformed

    private void btnPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceActionPerformed
        // TODO add your handling code here:
        PerformanceReportsJPanel panel = new PerformanceReportsJPanel();

        java.util.List<info5100.university.example.CourseSchedule.CourseSchedule> schedules =
                business.getDepartment().getAllCourseSchedules();

        panel.setSchedules(schedules);

        CardSequencePanel.add("PerformanceReportsJPanel", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnPerformanceActionPerformed

    private void btnTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionActionPerformed
        // TODO add your handling code here:
        TuitionInsightJPanel panel = new TuitionInsightJPanel(facultyProfile);
        CardSequencePanel.add("TuitionInsightJPanel", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnTuitionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngCourses;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnPerformance;
    private javax.swing.JButton btnStudentsProfiles;
    private javax.swing.JButton btnTuition;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
