/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 70787
 */
public class ManageCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCoursesJPanel
     */
    private final Business business;
    private final FacultyProfile facultyProfile;
    private final javax.swing.JPanel cardPanel;

    public ManageCoursesJPanel(Business b, FacultyProfile fp, javax.swing.JPanel clp) {
        initComponents();
        this.business = b;
        this.facultyProfile = fp;
        this.cardPanel = clp;
        populateTable();
    }
    private FacultyProfile safeFacultyOf(CourseOffer co) {
    try {
        return co.getFacultyProfile();   // this may NPE if no assignment in current CourseOffer impl
    } catch (Exception ex) {
        return null;
    }
}
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tableCourse.getModel();
        dtm.setRowCount(0);

        Department dept = business.getDepartment();
        CourseSchedule cs = dept.getCourseSchedule("Fall 2025");  // change semester if needed
        if (cs == null) return;

        List<CourseOffer> offers = cs.getSchedule();
        for (CourseOffer co : offers) {
            String courseName = co.getSubjectCourse().getName();  

            // Faculty: use safe wrapper to avoid NPE from CourseOffer.getFacultyProfile()
            info5100.university.example.Persona.Faculty.FacultyProfile fp = safeFacultyOf(co);
            String facultyName = (fp == null) ? "Unassigned" : fp.getPerson().getName();

            Object[] row = new Object[]{
                co.getCourseNumber(),
                courseName,
                co.getSeatCount(),
                co.getEnrolledCount(),
                facultyName
            };
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTitle.setText("Manage Courses");

        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Seats", "Enrolled", "Faculty"
            }
        ));
        jScrollPane1.setViewportView(tableCourse);

        btnBack.setText("<<  Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssign)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAssign))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:       
        cardPanel.remove(this);
        ((java.awt.CardLayout) cardPanel.getLayout()).previous(cardPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:        
    int selectedRow = tableCourse.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    String courseNumber = (String) tableCourse.getValueAt(selectedRow, 0);
    Department dept = business.getDepartment();
    CourseSchedule cs = dept.getCourseSchedule("Fall 2025");
    if (cs == null) {
        JOptionPane.showMessageDialog(this, "Course schedule not found for Fall 2025.");
        return;
    }

    CourseOffer co = cs.getCourseOfferByNumber(courseNumber);
    if (co == null) {
        JOptionPane.showMessageDialog(this, "Selected course not found.");
        return;
    }

    // Use the safe wrapper instead of calling co.getFacultyProfile() directly
    if (safeFacultyOf(co) != null) {
        JOptionPane.showMessageDialog(this, "This course already has an instructor assigned.");
        return;
    }

    facultyProfile.assignToCourse(co);
    JOptionPane.showMessageDialog(this, "You are now assigned to teach " + co.getSubjectCourse().getName());
    populateTable();

    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tableCourse;
    // End of variables declaration//GEN-END:variables
}
