/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 70787
 */
public class ManageCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCoursesJPanel
     */
    private final Business business;
    private final FacultyProfile facultyProfile;
    private final javax.swing.JPanel cardPanel;

    public ManageCoursesJPanel(Business b, FacultyProfile fp, javax.swing.JPanel clp) {
        initComponents();
        this.business = b;
        this.facultyProfile = fp;
        this.cardPanel = clp;
        populateTable();
        
        Department dept = business.getDepartment();
        java.util.List<info5100.university.example.Persona.Faculty.FacultyProfile> allTeachers =
        dept.getFacultyDirectory().getTeacherList();

        java.util.Vector<String> facultyNames = new java.util.Vector<>();
        for (info5100.university.example.Persona.Faculty.FacultyProfile f : allTeachers) {
            facultyNames.add(f.getPerson().getName());
        }

        javax.swing.JComboBox<String> facultyCombo = new javax.swing.JComboBox<>(facultyNames);

        tableCourse.getColumnModel().getColumn(4)
                   .setCellEditor(new javax.swing.DefaultCellEditor(facultyCombo));
        
        String[] scheduleOptions = {
            "Monday 09:00–11:00",
            "Monday 13:00–15:00",
            "Tuesday 09:00–11:00",
            "Tuesday 13:00–15:00",
            "Wednesday 09:00–11:00",
            "Wednesday 13:00–15:00",
            "Thursday 09:00–11:00",
            "Friday 09:00–11:00",
            "Friday 13:00–15:00",
            "Saturday 09:00–12:00"
        };
        javax.swing.JComboBox<String> comboBox = new javax.swing.JComboBox<>(scheduleOptions);
        tableCourse.getColumnModel().getColumn(5).setCellEditor(new javax.swing.DefaultCellEditor(comboBox));
    }
    private FacultyProfile safeFacultyOf(CourseOffer co) {
    try {
        return co.getFacultyProfile();   // this may NPE if no assignment in current CourseOffer impl
    } catch (Exception ex) {
        return null;
    }
}
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tableCourse.getModel();
        dtm.setRowCount(0);

        Department dept = business.getDepartment();
        CourseSchedule cs = dept.getCourseSchedule("Fall 2025");  // change semester if needed
        if (cs == null) return;

        List<CourseOffer> offers = cs.getSchedule();
        for (CourseOffer co : offers) {
            String courseName = co.getSubjectCourse().getName();  

            // Faculty: use safe wrapper to avoid NPE from CourseOffer.getFacultyProfile()
            info5100.university.example.Persona.Faculty.FacultyProfile fp = safeFacultyOf(co);
            String facultyName = (fp == null) ? "Unassigned" : fp.getPerson().getName();

            Object[] row = new Object[]{
                co.getCourseNumber(),
                courseName,
                co.getSeatCount(),
                co.getEnrolledCount(),
                facultyName,
                co.getScheduleTime(),    
            };
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSyllabus = new javax.swing.JButton();
        btnTogEnroll = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTitle.setText("Manage Courses");

        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Seats", "Enrolled", "Faculty", "schedule"
            }
        ));
        jScrollPane1.setViewportView(tableCourse);

        btnBack.setText("<<  Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSyllabus.setText("Syllabus");
        btnSyllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyllabusActionPerformed(evt);
            }
        });

        btnTogEnroll.setText("ToggleEnrollment");
        btnTogEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTogEnrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(btnSyllabus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTogEnroll)
                .addGap(143, 143, 143)
                .addComponent(btnSave)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave)
                    .addComponent(btnSyllabus)
                    .addComponent(btnTogEnroll))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:       
        cardPanel.remove(this);
        ((java.awt.CardLayout) cardPanel.getLayout()).previous(cardPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:        
        Department dept = business.getDepartment();
        CourseSchedule cs = dept.getCourseSchedule("Fall 2025");
        if (cs == null) {
            JOptionPane.showMessageDialog(this, "No course schedule found.");
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) tableCourse.getModel();
        int rowCount = dtm.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            String courseNum   = String.valueOf(dtm.getValueAt(i, 0));  // Course Number
            String courseName  = String.valueOf(dtm.getValueAt(i, 1));  // Course Name
            Object seatObj     = dtm.getValueAt(i, 2);                  // Seats
            Object enrolledObj = dtm.getValueAt(i, 3);                  // Enrolled
            String facultyName = String.valueOf(dtm.getValueAt(i, 4));  // Faculty
            String schedule    = String.valueOf(dtm.getValueAt(i, 5));  // Schedule
            
            CourseOffer co = cs.getCourseOfferByNumber(courseNum);
            if (co == null) continue;

            co.getSubjectCourse().setName(courseName);  
            
            co.setScheduleTime(schedule);              

            try {
                int newSeatCount = Integer.parseInt(String.valueOf(seatObj));
                if (newSeatCount > 0 && newSeatCount != co.getSeatCount()) {
                    co.generatSeats(newSeatCount); 
                }
            } catch (NumberFormatException e) {
            }
            if (facultyName != null && !facultyName.isEmpty()) {
                info5100.university.example.Persona.Faculty.FacultyDirectory fd = dept.getFacultyDirectory();
                for (info5100.university.example.Persona.Faculty.FacultyProfile f : fd.getTeacherList()) {
                    if (facultyName.equals(f.getPerson().getName())) {
                        co.assignFaculty(f);
                        break;
                    }
                }
            }
        }

        JOptionPane.showMessageDialog(this, "Schedule times saved successfully!");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSyllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyllabusActionPerformed
        // TODO add your handling code here:                                           
        int selectedRow = tableCourse.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
            return;
        }

        // 取选中课程号
        String courseNum = String.valueOf(tableCourse.getValueAt(selectedRow, 0));

        Department dept = business.getDepartment();
        CourseSchedule cs = dept.getCourseSchedule("Fall 2025");
        CourseOffer co = cs.getCourseOfferByNumber(courseNum);
        if (co == null) {
            JOptionPane.showMessageDialog(this, "Course not found.");
            return;
        }

        // 让用户选择文件或输入大纲内容
        String[] options = {"Select File", "Enter Text"};
        int choice = JOptionPane.showOptionDialog(
            this,
            "How do you want to upload the syllabus?",
            "Upload Syllabus",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            options,
            options[0]
        );

        if (choice == 0) {
            // 选择文件
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            int result = fileChooser.showOpenDialog(this);
            if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
                String filePath = fileChooser.getSelectedFile().getAbsolutePath();
                co.setSyllabus(filePath);
                JOptionPane.showMessageDialog(this, "Syllabus uploaded: " + filePath);
            }
        } else if (choice == 1) {
            // 手动输入
            String syllabusText = JOptionPane.showInputDialog(this, "Enter syllabus text:", co.getSyllabus());
            if (syllabusText != null && !syllabusText.trim().isEmpty()) {
                co.setSyllabus(syllabusText);
                JOptionPane.showMessageDialog(this, "Syllabus updated.");
            }
        }
    
    }//GEN-LAST:event_btnSyllabusActionPerformed

    private void btnTogEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTogEnrollActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableCourse.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
            return;
        }

        String courseNum = String.valueOf(tableCourse.getValueAt(selectedRow, 0));

        Department dept = business.getDepartment();
        CourseSchedule cs = dept.getCourseSchedule("Fall 2025");
        CourseOffer co = cs.getCourseOfferByNumber(courseNum);
        if (co == null) {
            JOptionPane.showMessageDialog(this, "Course not found.");
            return;
        }

        // 切换状态
        if (co.isEnrollmentOpen()) {
            co.closeEnrollment();
            JOptionPane.showMessageDialog(this, "Enrollment closed for course " + courseNum);
        } else {
            co.openEnrollment();
            JOptionPane.showMessageDialog(this, "Enrollment opened for course " + courseNum);
        }

        populateTable();
    }//GEN-LAST:event_btnTogEnrollActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSyllabus;
    private javax.swing.JButton btnTogEnroll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tableCourse;
    // End of variables declaration//GEN-END:variables
}
