/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

/**
 *
 * @author 70787
 */
import info5100.university.example.Persona.Faculty.FacultyAssignment;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Persona.StudentProfile;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class ManageStudentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudentsJPanel
     */
    private FacultyProfile faculty;
    private CourseOffer selectedCourse;
    
    public ManageStudentsJPanel(FacultyProfile faculty) {
        
        initComponents();
        this.faculty = faculty;
        populateCourseCombo();
    }

    private void populateCourseCombo() {
    comboCourse.removeAllItems();
    for (FacultyAssignment fa : faculty.getFacultyAssignments()) {
        comboCourse.addItem(fa.getCourseOffer());
    }
}


    private void populateStudentTable() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Student ID", "Name", "Score (0-100)", "GPA", "Letter"}, 0);
        tableStudentList.setModel(model);
        model.setRowCount(0);

        if (selectedCourse == null) return;

        ArrayList<SeatAssignment> seatList = selectedCourse.getSeatAssignments();
        for (SeatAssignment sa : seatList) {
            StudentProfile sp = sa.getStudentProfile();
            if (sp == null || sp.getPerson() == null) continue;

            Object[] row = new Object[5];
            row[0] = sp.getPerson().getPersonId();
            row[1] = sp.getPerson().getName();
            row[2] = sa.getRawScore();
            row[3] = sa.getGrade();        
            model.addRow(row);
        }
    }
    private void rankStudents() {
    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }
    ArrayList<SeatAssignment> seatList = selectedCourse.getSeatAssignments();
    seatList.sort(Comparator.comparingDouble(SeatAssignment::getGrade).reversed());

    double total = 0;
    for (SeatAssignment sa : seatList) total += sa.getGrade();
    double avg = seatList.isEmpty() ? 0 : total / seatList.size();

    // 用排序后的 seatList 重绘表格（与上面 populateStudentTable 的5列保持一致）
    DefaultTableModel model = (DefaultTableModel) tableStudentList.getModel();
    model.setRowCount(0);
    for (SeatAssignment sa : seatList) {
        StudentProfile sp = sa.getStudentProfile();
        if (sp == null || sp.getPerson() == null) continue;
        Object[] row = new Object[5];
        row[0] = sp.getPerson().getPersonId();
        row[1] = sp.getPerson().getName();
        row[2] = sa.getRawScore();
        row[3] = sa.getGrade();
        row[4] = sa.getLetterGrade();
        model.addRow(row);
    }
    lblGPA.setText(String.format("Class GPA: %.2f", avg));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCourse = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStudentList = new javax.swing.JTable();
        fieldGrade = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnRank = new javax.swing.JButton();
        lblGPA = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();

        comboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseActionPerformed(evt);
            }
        });

        tableStudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Grade", "Letter"
            }
        ));
        jScrollPane1.setViewportView(tableStudentList);

        btnUpdate.setText("Update Grade");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRank.setText("Rank Students");
        btnRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankActionPerformed(evt);
            }
        });

        lblGPA.setText("Compute GPA");

        btnView.setText("ViewTranscript");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btnView)
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRank))
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGPA))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnRank)
                    .addComponent(btnView))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseActionPerformed
        // TODO add your handling code here:
        selectedCourse = (CourseOffer) comboCourse.getSelectedItem();
        populateStudentTable();
    }//GEN-LAST:event_comboCourseActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableStudentList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student first.");
            return;
        }

        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
            return;
        }

        try {
            double grade = Double.parseDouble(fieldGrade.getText().trim());
            if (grade < 0 || grade > 100) {
                JOptionPane.showMessageDialog(this, "Please enter a score between 0 and 100.");
                return;
            }
            String studentId = (String) tableStudentList.getValueAt(selectedRow, 0);

            boolean updated = false;
            for (SeatAssignment sa : selectedCourse.getSeatAssignments()) {
                StudentProfile ssp = sa.getStudentProfile();
                if (ssp != null && ssp.getPerson() != null 
                    && ssp.getPerson().getPersonId().equals(studentId)) {
                    sa.setGrade(grade);  
                    updated = true;
                    break;
                }
            }
            if (!updated) {
                JOptionPane.showMessageDialog(this, "Update failed: student not found in this course.");
                return;
            }
            populateStudentTable();
            fieldGrade.setText("");
            JOptionPane.showMessageDialog(this, "Grade updated successfully.");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid grade input.");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankActionPerformed
        // TODO add your handling code here:
       
    rankStudents();
    }//GEN-LAST:event_btnRankActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableStudentList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student first.");
            return;
        }
        String studentId = (String) tableStudentList.getValueAt(selectedRow, 0);
        StudentProfile sp = null;
        for (SeatAssignment sa : selectedCourse.getSeatAssignments()) {
            if (sa.getStudentProfile().getPerson().getPersonId().equals(studentId)) {
                sp = sa.getStudentProfile();
                break;
            }
        }
        if (sp != null) {
            ViewTranscriptJPanel panel = new ViewTranscriptJPanel(sp);
            JOptionPane.showMessageDialog(this, panel, 
                "Transcript Summary for " + sp.getPerson().getName(), JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRank;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<CourseOffer> comboCourse;
    private javax.swing.JTextField fieldGrade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JTable tableStudentList;
    // End of variables declaration//GEN-END:variables
}
