/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.SeatAssignment;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.Component;
import java.util.*;
import java.io.FileWriter;
import java.io.IOException;
/**
 *
 * @author 70787
 */
public class PerformanceReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerformanceReports
     */
    private java.util.List<CourseSchedule> allSchedules = new java.util.ArrayList<>();
    public PerformanceReportsJPanel() {
        initComponents();
        initReportUI();
        btnExport.setEnabled(false);             
        cmbCourse.setRenderer(new DefaultListCellRenderer(){ 
            @Override public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                String text = (value instanceof CourseOffer) ? value.toString() : (value == null ? "" : value.toString());
                return super.getListCellRendererComponent(list, text, index, isSelected, cellHasFocus);
            }
        });
    }
    private void initReportUI() {
        // 保护表格不可编辑
        tblReport.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Metric","Value"}) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        });
        populateSemesterCombo();
    }
    public void setSchedules(java.util.List<CourseSchedule> schedules) {
        this.allSchedules = (schedules == null) ? new java.util.ArrayList<>() : schedules;
        populateSemesterCombo();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        lblCourse = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        btnExport = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTitle.setText("Performance Reports");

        lblSemester.setText("Semester");

        cmbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemesterActionPerformed(evt);
            }
        });

        lblCourse.setText("Course");

        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Metric", "Value"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        btnExport.setText("Export CSV");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSemester)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCourse)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExport)))))
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(lblCourse)
                    .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
        refreshReportTable();
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void cmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemesterActionPerformed
        // TODO add your handling code here:
        populateCourseCombo();
        refreshReportTable();
    }//GEN-LAST:event_cmbSemesterActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        CourseOffer offer = getSelectedOffer();
        if (offer == null) {
            JOptionPane.showMessageDialog(this, "Please select a course to export.", "No course", JOptionPane.WARNING_MESSAGE);
            return;
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Export Course Performance as CSV");
        chooser.setSelectedFile(new java.io.File(safeFileName(buildCsvDefaultName(offer)) + ".csv"));
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try (FileWriter fw = new FileWriter(chooser.getSelectedFile())) {
                String semester = (String) cmbSemester.getSelectedItem();
                java.util.Map<String,Object> metrics = computeMetrics(offer);
                writeCsv(fw, semester, offer, metrics);
                JOptionPane.showMessageDialog(this, "Exported successfully.", "Export", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Export failed: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportActionPerformed
    private void populateSemesterCombo() {
        cmbSemester.removeAllItems();
        java.util.Set<String> sems = new java.util.TreeSet<>(); // range
        for (CourseSchedule cs : allSchedules) {
            if (cs != null && cs.getSemester() != null) sems.add(cs.getSemester());
        }
        cmbSemester.addItem("All");         
        for (String s : sems) cmbSemester.addItem(s);
        cmbSemester.setSelectedIndex(0);
        populateCourseCombo();
    }
    
    private void populateCourseCombo() {
        cmbCourse.removeAllItems();
        String sem = (String) cmbSemester.getSelectedItem();

        java.util.List<CourseOffer> offers = new java.util.ArrayList<>();
        for (CourseSchedule cs : allSchedules) {
            if (cs == null) continue;
            boolean match = (sem == null || "All".equals(sem)) || sem.equals(cs.getSemester());
            if (!match) continue;

            java.util.List<CourseOffer> list = cs.getSchedule(); // 
            if (list != null) offers.addAll(list);
        }

        //  toString() range
        java.util.LinkedHashMap<String, CourseOffer> unique = new java.util.LinkedHashMap<>();
        for (CourseOffer co : offers) {
            if (co == null) continue;
            unique.put(co.toString(), co);
        }
        java.util.List<String> keys = new java.util.ArrayList<>(unique.keySet());
        java.util.Collections.sort(keys);
        for (String k : keys) cmbCourse.addItem(unique.get(k));

        if (cmbCourse.getItemCount() == 0) {
            DefaultTableModel model = (DefaultTableModel) tblReport.getModel();
            model.setRowCount(0);
            model.addRow(new Object[]{"Info", "No courses found for this semester."});
        }
    }

    private void refreshReportTable() {
        CourseOffer offer = getSelectedOffer();
        DefaultTableModel model = (DefaultTableModel) tblReport.getModel();

        model.setColumnIdentifiers(new Object[]{"Metric", "Value"});
        model.setRowCount(0);

        if (offer == null) {
            model.addRow(new Object[]{"Info", "Please select a course."});
            return;
        }

        java.util.Map<String,Object> metrics = computeMetrics(offer);
        model.addRow(new Object[]{"Average Grade", String.format(java.util.Locale.US, "%.2f", (Double)metrics.get("avg"))});
        model.addRow(new Object[]{"Enrollment Count", metrics.get("enroll")});

        @SuppressWarnings("unchecked")
        java.util.Map<String,Integer> dist = (java.util.Map<String,Integer>) metrics.get("dist");
        String[] letters = {"A","B","C","D","F"};
        for (String lt : letters) {
            model.addRow(new Object[]{"Count " + lt, dist.getOrDefault(lt, 0)});
        }
        btnExport.setEnabled(true);  
    }

    private java.util.Map<String,Object> computeMetrics(CourseOffer offer) {
        java.util.Map<String,Object> out = new java.util.HashMap<>();
        java.util.List<SeatAssignment> seats = offer.getSeatAssignments(); 
        int n = 0; double total = 0.0;
        java.util.Map<String,Integer> dist = new java.util.HashMap<>();

        if (seats != null) {
            for (SeatAssignment sa : seats) {
                if (sa == null) continue;

                double g = sa.getGrade();
                if (!Double.isNaN(g) && g >= 0) { total += g; n++; }

                String letter = null;
                try { letter = sa.getLetterGrade(); } catch (Throwable ignore) {}
                if (letter == null || letter.trim().isEmpty()) letter = numericToLetter(g);
                letter = letter.toUpperCase(java.util.Locale.ROOT);
                if (!java.util.Arrays.asList("A","B","C","D","F").contains(letter)) {
                    letter = numericToLetter(g);
                }
                dist.put(letter, dist.getOrDefault(letter, 0) + 1);
            }
        }
        double avg = (n == 0) ? 0.0 : total / n;
        out.put("avg", avg);
        out.put("enroll", (seats == null) ? 0 : seats.size());
        out.put("dist", dist);
        return out;
    }

    private String numericToLetter(double g) {
        if (Double.isNaN(g)) return "F";
        if (g >= 90) return "A";
        if (g >= 80) return "B";
        if (g >= 70) return "C";
        if (g >= 60) return "D";
        return "F";
    }

    private CourseOffer getSelectedOffer() {
        Object sel = cmbCourse.getSelectedItem();
        return (sel instanceof CourseOffer) ? (CourseOffer) sel : null;
    }

    private String buildCsvDefaultName(CourseOffer offer) {
        String sem = (String) cmbSemester.getSelectedItem();
        String courseLabel = offer.toString().replaceAll("[\\\\/:*?\"<>|]", "_");
        return (sem == null ? "All" : sem) + "_" + courseLabel + "_Performance";
    }

    private String safeFileName(String s) {
        return s.replaceAll("[\\\\/:*?\"<>|]", "_");
    }

    private void writeCsv(java.io.FileWriter fw, String semester, CourseOffer offer, java.util.Map<String,Object> metrics) throws java.io.IOException {
        fw.write("Semester,Course,Average Grade,Enrollment,Count A,Count B,Count C,Count D,Count F\n");
        @SuppressWarnings("unchecked")
        java.util.Map<String,Integer> dist = (java.util.Map<String,Integer>) metrics.get("dist");
        String line = String.format(java.util.Locale.US, "%s,%s,%.2f,%d,%d,%d,%d,%d,%d\n",
                quote(semester),
                quote(offer.toString()),
                (Double) metrics.get("avg"),
                (metrics.get("enroll") instanceof Integer ? (Integer) metrics.get("enroll") : 0),
                dist.getOrDefault("A",0),
                dist.getOrDefault("B",0),
                dist.getOrDefault("C",0),
                dist.getOrDefault("D",0),
                dist.getOrDefault("F",0));
        fw.write(line);
        fw.flush();
    }

    private String quote(String s) {
        if (s == null) return "";
        return "\"" + s.replace("\"", "\"\"") + "\"";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JComboBox<CourseOffer> cmbCourse;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
