/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Faculty.FacultyAssignment;
import info5100.university.example.CourseSchedule.CourseOffer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 70787
 */
public class TuitionInsightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TuitionInsightJPanel
     */
    private FacultyProfile faculty;
    public TuitionInsightJPanel(FacultyProfile faculty) {
        initComponents();
        this.faculty = faculty;
        populateTuitionTable();
    }

    private void populateTuitionTable() {
    DefaultTableModel model = (DefaultTableModel) tblTuition.getModel();
    model.setRowCount(0); 

    double totalCollected = 0;

    for (FacultyAssignment fa : faculty.getFacultyAssignments()) {
        CourseOffer co = fa.getCourseOffer();
        int enrolled = co.getEnrolledCount();
        int tuitionPerStudent = co.getSubjectCourse().getCoursePrice(); 
        double total = enrolled * tuitionPerStudent;
        totalCollected += total;

        Object[] row = new Object[4];
        row[0] = co.getSubjectCourse().getName();
        row[1] = enrolled;
        row[2] = tuitionPerStudent;
        row[3] = total;
        model.addRow(row);
    }

    lblTotal.setText(String.format("Total Tuition Collected: $%.2f", totalCollected));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTuition = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTitle.setText("Tuition");

        tblTuition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course", "Enrolled Student", "Tuition per Student", "Total Tution"
            }
        ));
        jScrollPane1.setViewportView(tblTuition);

        lblTotal.setText("Total Tuition:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblTotal)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblTotal)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblTuition;
    // End of variables declaration//GEN-END:variables
}
