/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import java.awt.BorderLayout;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.CourseSchedule.CourseOffer;
/**
 *
 * @author 70787
 */
public class ViewTranscriptJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewTranscriptJPanel
     */
    public ViewTranscriptJPanel(StudentProfile student) {
        initComponents();                
        setLayout(new BorderLayout());   

        JTable table = new JTable(new DefaultTableModel(
            new Object[]{"Course", "Semester", "Grade", "Letter"}, 0));
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        for (SeatAssignment sa : student.getCourseList()) {
            CourseOffer co = sa.getCourseOffer();
            String semester = safeSemester(co);         
            double g = sa.getGrade();
            String letter = toLetter(g);         
            model.addRow(new Object[]{
                co.getSubjectCourse().getName(),
                semester,
                g,
                letter
            });
        }
        add(new JScrollPane(table), BorderLayout.CENTER);
    }
    private String safeSemester(CourseOffer co) {
        try {
            return co.getCourseSchedule() == null ? "TBD" : co.getCourseSchedule().getSemester();
        } catch (Exception e) {
            return "TBD";
        }
    }


    private String toLetter(double gpaPoint) {
        if (gpaPoint >= 4.0) return "A";
        if (gpaPoint >= 3.7) return "A-";
        if (gpaPoint >= 3.3) return "B+";
        if (gpaPoint >= 3.0) return "B";
        if (gpaPoint >= 2.7) return "B-";
        if (gpaPoint >= 2.3) return "C+";
        if (gpaPoint >= 2.0) return "C";
        if (gpaPoint >= 1.7) return "C-";
        return "F";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
