/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;

import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public AdminRoleWorkAreaJPanel(Business b, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageUserAccounts = new javax.swing.JButton();
        btnManageFacultyRecords = new javax.swing.JButton();
        btnManagePersons = new javax.swing.JButton();
        btnViewAnalytics = new javax.swing.JButton();
        btnManageStudentRecords = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnManageUserAccounts.setBackground(new java.awt.Color(102, 153, 255));
        btnManageUserAccounts.setFont(getFont());
        btnManageUserAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUserAccounts.setText("Administer User Accounts");
        btnManageUserAccounts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageUserAccounts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageUserAccounts.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageUserAccounts.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageFacultyRecords.setBackground(new java.awt.Color(102, 153, 255));
        btnManageFacultyRecords.setFont(getFont());
        btnManageFacultyRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnManageFacultyRecords.setText("Manage Faculty");
        btnManageFacultyRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageFacultyRecords.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageFacultyRecords.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageFacultyRecords.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageFacultyRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFacultyRecordsActionPerformed(evt);
            }
        });

        btnManagePersons.setBackground(new java.awt.Color(102, 153, 255));
        btnManagePersons.setFont(getFont());
        btnManagePersons.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePersons.setText("Register  Persons (HR)");
        btnManagePersons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManagePersons.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManagePersons.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManagePersons.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManagePersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonsActionPerformed(evt);
            }
        });

        btnViewAnalytics.setBackground(new java.awt.Color(102, 153, 255));
        btnViewAnalytics.setFont(getFont());
        btnViewAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAnalytics.setText("View Analytics");
        btnViewAnalytics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewAnalytics.setMaximumSize(new java.awt.Dimension(145, 40));
        btnViewAnalytics.setMinimumSize(new java.awt.Dimension(20, 20));
        btnViewAnalytics.setPreferredSize(new java.awt.Dimension(240, 25));
        btnViewAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAnalyticsIdentifyEventsActionPerformed(evt);
            }
        });

        btnManageStudentRecords.setBackground(new java.awt.Color(102, 153, 255));
        btnManageStudentRecords.setFont(getFont());
        btnManageStudentRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStudentRecords.setText("Manage Students");
        btnManageStudentRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudentRecords.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudentRecords.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudentRecords.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudentRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentRecordsActionPerformed(evt);
            }
        });

        btnMyProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnMyProfile.setFont(getFont());
        btnMyProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProfile.setText("My Profile");
        btnMyProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnMyProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMyProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileIdentifyEventsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageFacultyRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManagePersons, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudentRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePersons, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageFacultyRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudentRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserAccountsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageUserAccountsJPanel manageUsersPanel = new ManageUserAccountsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", manageUsersPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnManageUserAccountsIdentifyResourceAssetsActionPerformed

    private void btnManagePersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonsActionPerformed
        // TODO add your handling code here:

        ManagePersonsJPanel managePersonsJPanel = new ManagePersonsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("Manage Persons", managePersonsJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnManagePersonsActionPerformed

    private void btnManageStudentRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentRecordsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnManageStudentRecordsActionPerformed

    private void btnViewAnalyticsIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAnalyticsIdentifyEventsActionPerformed
    }//GEN-LAST:event_btnViewAnalyticsIdentifyEventsActionPerformed

    private void btnManageFacultyRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFacultyRecordsActionPerformed
    }//GEN-LAST:event_btnManageFacultyRecordsActionPerformed

    private void btnMyProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileIdentifyEventsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMyProfileIdentifyEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageFacultyRecords;
    private javax.swing.JButton btnManagePersons;
    private javax.swing.JButton btnManageStudentRecords;
    private javax.swing.JButton btnManageUserAccounts;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnViewAnalytics;
    // End of variables declaration//GEN-END:variables

}
